### ISSUE TITLE
Unable to access uploaded assets

### ISSUE THREAD

**Issue by tmbn-dean** [olsgreen/webpack-s3-pusher#1]
I've configured as per the documentation and have successfully had assets compile and upload to the right location on AWS, my issue is that the assets are not publically accessible and there appears to be no way to configure them to be public as default.

Am I missing something in my config?
Do I need another package to make things public?

Lastly, is this plugin still actively developed. I came across it earlier today and the page I found says it was updated 9 hours ago (at the time of writing) yet github says the same release was created in October 2020

**Comment by olsgreen** [comment]
I originally wrote this for our public buckets, so the buckets default ACL was public, thus there was no need to set the ACL on each object.

We still use it in production, and periodically update it's dependencies.

I've just pushed a commit to the master to add the ability to specify the ACL to public which should solve your problems.

**Comment by olsgreen** [comment]
To add to the above I've just updated the docs and released 2.1.1.

All you should need todo is `nom update webpack-s3-pusher` to the latest version add the ACL option and set it to `public-read` as per the documentation.

Any problems give me a shout.
